#create a network and add our services into this network:
version: "3.7"

networks:
  codex-network:

services:

  config:
    build:
      context: ./config
      dockerfile: Dockerfile
      args:
        - APP_VERSION=0.1.0
    image: config
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8081:8888"
    networks:
      - codex-network
    volumes:
      - ${HOME}/codex/codex-config:/home/spring/codex-config
    command: java -jar codex/build/libs/config-0.1.0.jar

  catalog:
    build:
      context: ./catalog
      dockerfile: Dockerfile
      args:
        - APP_VERSION=0.0.1-SNAPSHOT
    image: catalog
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DEBUG=true
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6666
    ports:
      - "8082:8888"
      - "6666:6666"
    networks:
      - codex-network
    command: java -jar catalog/build/libs/catalog-${APP_VERSION}.jar

  security:
    build:
      context: ./security
      dockerfile: Dockerfile
      args:
        - APP_VERSION=0.0.1-SNAPSHOT
    image: security
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DEBUG=true
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6667
    ports:
      - "8083:8888"
      - "6667:6667"
    networks:
      - codex-network
    command: java -jar security/build/libs/security-${APP_VERSION}.jar

