#create a network and add our services into this network:
version: "3"

networks:
  codex-network:

services:

  config-server:
 
    image: thetyne/codex-config

    environment:
      - SPRING_PROFILES_ACTIVE=dev
    expose:
      - "8081"
    ports:
      - "8081:8888"
    networks:
      - codex-network
    volumes:
      - ${HOME}/codex/codex-config:/home/spring/codex-config
    command: java -jar codex/build/libs/config-0.1.0.jar

  catalog-server:
 
    image: thetyne/codex-catalog
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DEBUG=true
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6666
    ports:
      - "8082:8888"
      - "6666:6666"
    networks:
      - codex-network
    entrypoint: ["sh", "-c", "./wait-for-it.sh config-server:8888 -t 25 && ./run.sh"]
    command: java -jar catalog/build/libs/catalog-${APP_VERSION}.jar

  security-server:
 
    image: thetyne/codex-security

    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DEBUG=true
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:6667
    ports:
      - "8083:8888"
      - "6667:6667"
    networks:
      - codex-network
    entrypoint: ["sh", "-c", "./wait-for-it.sh config-server:8888 -t 25 && ./run.sh"]
    command: java -jar security/build/libs/security-${APP_VERSION}.jar

