apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: security-server
  name: security-server
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8888
  - name: "6667"
    port: 6667
    targetPort: 6667
  selector:
    io.kompose.service: security-server
status:
  loadBalancer: {}
